-- TRACKER_SYSTEM Supabase database backup/setup.
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.coordinates (
  id bigint generated by default as identity primary key,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  added_at varchar(50) not null,
  source varchar(50) not null default 'ESP32',
  status varchar(20) not null default 'Idle',
  created_at timestamptz not null default now(),
  constraint coordinates_status_check check (status in ('Idle', 'Moving', 'Latest'))
);

create index if not exists coordinates_created_at_idx
  on public.coordinates (created_at desc);

create index if not exists coordinates_source_created_at_idx
  on public.coordinates (source, created_at desc);

-- Optional sample data. You can delete this before importing if you want an empty table.
insert into public.coordinates (latitude, longitude, added_at, source, status)
values (14.5995120, 120.9842220, '2026-05-08 12:00 PM', 'Sample', 'Idle');
