-- Coordinates table for TRACKER_SYSTEM on Supabase.
-- Run this in Supabase Dashboard > SQL Editor.

create table if not exists public.coordinates (
  id bigint generated by default as identity primary key,
  latitude numeric(10, 7) not null,
  longitude numeric(10, 7) not null,
  added_at varchar(50) not null,
  source varchar(50) not null default 'ESP32',
  status varchar(20) not null default 'Idle',
  created_at timestamptz not null default now(),
  constraint coordinates_status_check check (status in ('Idle', 'Moving', 'Latest'))
);

create index if not exists coordinates_created_at_idx
  on public.coordinates (created_at desc);

create index if not exists coordinates_source_created_at_idx
  on public.coordinates (source, created_at desc);
